public enum ExerciseCatalog {
    public static let all: [Exercise] = [
        Exercise(id: "barbellSquat", name: "Приседания со штангой", movementPattern: MovementPatternCatalog.squat, isBuiltIn: true, techniqueDescription: "Со штангой на плечах присядьте до параллели бёдер с полом, сохраняя спину прямой, затем поднимитесь в исходное положение.", imageAssetName: "barbellSquat"),
        Exercise(id: "pullUp", name: "Подтягивания", movementPattern: MovementPatternCatalog.verticalPullBodyweight, isBuiltIn: true, techniqueDescription: "Возьмитесь за перекладину прямым хватом и подтянитесь, пока подбородок не окажется над перекладиной, затем плавно опуститесь.", imageAssetName: "pullUp"),
        Exercise(id: "romanianDeadlift", name: "Румынская тяга", movementPattern: MovementPatternCatalog.hipHinge, isBuiltIn: true, techniqueDescription: "Со штангой в прямых руках наклонитесь вперёд от бёдер, чуть сгибая колени, пока не почувствуете растяжение задней поверхности бедра, затем вернитесь в исходное положение.", imageAssetName: "romanianDeadlift"),
        Exercise(id: "gluteBridge", name: "Ягодичный мост", movementPattern: MovementPatternCatalog.hipExtension, isBuiltIn: true, techniqueDescription: "Лёжа на спине с согнутыми коленями поднимите таз вверх, напрягая ягодицы, затем плавно опустите.", imageAssetName: "gluteBridge"),
        Exercise(id: "legPress", name: "Жим ногами", movementPattern: MovementPatternCatalog.squatMachine, isBuiltIn: true, techniqueDescription: "Сидя в тренажёре, согните колени до угла 90 градусов и выжмите платформу вверх, не разгибая колени полностью.", imageAssetName: "legPress"),
        Exercise(id: "lyingLegCurl", name: "Сгибание ног лёжа", movementPattern: MovementPatternCatalog.legCurl, isBuiltIn: true, techniqueDescription: "Лёжа на животе, согните ноги в коленях, подводя валик тренажёра к ягодицам, затем плавно вернитесь в исходное положение.", imageAssetName: "lyingLegCurl"),
        Exercise(id: "cableHipAbduction", name: "Отведение ноги в кроссовере", movementPattern: MovementPatternCatalog.hipAbduction, isBuiltIn: true, techniqueDescription: "Стоя боком к блоку с манжетой на щиколотке, отведите прямую ногу в сторону, затем плавно верните обратно.", imageAssetName: "cableHipAbduction"),
        Exercise(id: "seatedHipAbduction", name: "Разводка ног сидя", movementPattern: MovementPatternCatalog.hipAbduction, isBuiltIn: true, techniqueDescription: "Сидя в тренажёре с упорами на внешней стороне бёдер, разведите колени в стороны против сопротивления, затем плавно сведите обратно.", imageAssetName: "seatedHipAbduction"),
        Exercise(id: "pushUp", name: "Отжимания", movementPattern: MovementPatternCatalog.horizontalPress, isBuiltIn: true, techniqueDescription: "В упоре лёжа согните руки, опуская грудь к полу, затем выжмите тело вверх, сохраняя корпус прямым.", imageAssetName: "pushUp"),
        Exercise(id: "crunch", name: "Пресс", movementPattern: MovementPatternCatalog.crunch, isBuiltIn: true, techniqueDescription: "Лёжа на спине с согнутыми коленями оторвите лопатки от пола, скручиваясь к тазу, затем плавно вернитесь.", imageAssetName: "crunch"),
        Exercise(id: "wideGripLatPulldown", name: "Вертикальная тяга (широкий хват)", movementPattern: MovementPatternCatalog.verticalPullCable, isBuiltIn: true, techniqueDescription: "Сидя в тренажёре, широким хватом потяните рукоять вниз к верху груди, затем плавно верните вес наверх.", imageAssetName: "wideGripLatPulldown"),
        Exercise(id: "closeGripLatPulldown", name: "Вертикальная тяга (узкий хват)", movementPattern: MovementPatternCatalog.verticalPullCable, isBuiltIn: true, techniqueDescription: "Сидя в тренажёре, узким хватом потяните рукоять вниз к груди, сводя лопатки, затем плавно верните вес наверх.", imageAssetName: "closeGripLatPulldown"),
        Exercise(id: "seatedCableRow", name: "Горизонтальная тяга", movementPattern: MovementPatternCatalog.horizontalPull, isBuiltIn: true, techniqueDescription: "Сидя у блока с прямой спиной потяните рукоять к животу, сводя лопатки, затем плавно верните вес вперёд.", imageAssetName: "seatedCableRow"),
        Exercise(id: "pullover", name: "Пуловер", movementPattern: MovementPatternCatalog.pullover, isBuiltIn: true, techniqueDescription: "В кроссовере или с гантелью прямыми руками опустите вес назад за голову, затем верните его над грудью.", imageAssetName: "pullover"),
        Exercise(id: "dumbbellBicepCurl", name: "Подъём гантелей на бицепс", movementPattern: MovementPatternCatalog.bicepCurl, isBuiltIn: true, techniqueDescription: "Стоя с гантелями в опущенных руках, согните руки в локтях, поднимая гантели к плечам, затем плавно опустите.", imageAssetName: "dumbbellBicepCurl"),
        Exercise(id: "seatedDumbbellPress", name: "Жим гантелей сидя", movementPattern: MovementPatternCatalog.overheadPressSeated, isBuiltIn: true, techniqueDescription: "Сидя с гантелями на уровне плеч, выжмите их вверх над головой, затем плавно опустите обратно.", imageAssetName: "seatedDumbbellPress"),
        Exercise(id: "cableTricepPushdown", name: "Разгибание рук (верхний блок)", movementPattern: MovementPatternCatalog.tricepExtensionCable, isBuiltIn: true, techniqueDescription: "Стоя у верхнего блока, разогните руки в локтях, отжимая рукоять вниз, затем плавно вернитесь в исходное положение.", imageAssetName: "cableTricepPushdown"),
        Exercise(id: "skullCrusher", name: "Французский жим", movementPattern: MovementPatternCatalog.tricepExtensionLying, isBuiltIn: true, techniqueDescription: "Лёжа со штангой или гантелями над грудью, согните руки в локтях, опуская вес ко лбу, затем разогните руки обратно.", imageAssetName: "skullCrusher"),
        Exercise(id: "standingLateralRaise", name: "Разведение гантелей стоя", movementPattern: MovementPatternCatalog.lateralRaise, isBuiltIn: true, techniqueDescription: "Стоя с гантелями по бокам, поднимите прямые руки в стороны до уровня плеч, затем плавно опустите.", imageAssetName: "standingLateralRaise"),
        Exercise(id: "standingDumbbellPress", name: "Жим гантелей стоя", movementPattern: MovementPatternCatalog.overheadPressStanding, isBuiltIn: true, techniqueDescription: "Стоя с гантелями на уровне плеч, выжмите их вверх над головой, не прогибаясь в пояснице, затем опустите обратно.", imageAssetName: "standingDumbbellPress"),
        Exercise(id: "reverseMachineFly", name: "Обратные разведения в тренажёре", movementPattern: MovementPatternCatalog.lateralRaise, isBuiltIn: true, techniqueDescription: "Сидя лицом к тренажёру, разведите руки в стороны и назад, сводя лопатки, затем плавно верните рукояти вперёд.", imageAssetName: "reverseMachineFly"),
        Exercise(id: "hyperextension", name: "Гиперэкстензия", movementPattern: MovementPatternCatalog.backExtension, isBuiltIn: true, techniqueDescription: "Лёжа животом на тренажёре с зафиксированными ногами, опустите корпус вниз, затем поднимите его до прямой линии с бёдрами.", imageAssetName: "hyperextension"),
        Exercise(id: "bulgarianSplitSquat", name: "Болгарские выпады", movementPattern: MovementPatternCatalog.lunge, isBuiltIn: true, techniqueDescription: "Поставив одну ногу на возвышение сзади, присядьте на опорной ноге до параллели бедра с полом, затем вернитесь в исходное положение.", imageAssetName: "bulgarianSplitSquat")
    ]

    public static func exercise(id: String) -> Exercise? {
        all.first { $0.id == id }
    }
}
